##############################################################################
# Developed by: Matthew Bone
# Last Updated: 08/02/2021
# Updated by: Matthew Bone
#
# Contact Details:
# Bristol Composites Institute (BCI)
# Department of Aerospace Engineering - University of Bristol
# Queen's Building - University Walk
# Bristol, BS8 1TR
# U.K.
# Email - matthew.bone@bristol.ac.uk
#
# File Description:
# Converts LAMMPS 'read_data' input files into LAMMPS molecule format files.
# Designed to work with LAMMPS data generated from Moltemplate, but can work
# for any LAMMPS data if it satisfies the header format in Assumptions.

# Assumptions:
# LAMMPS Atom Type is full
# That the header of the file operates in the standard format:
# Comment
#
#      a  atoms
#      b  bonds
#      c  angles
#      d  dihedrals
#      e  impropers

#      f  atom types
#      g bond types
#      h  angle types
#      i  dihedral types
#      j  improper types

#   x1 x2 xlo xhi
#   y1 y2 ylo yhi
#   z1 z2 zlo zhi
##############################################################################

import os
import re
import sys
from LammpsTreatmentFuncs import clean_data, find_sections, get_data, add_section_keyword, save_text_file, refine_data

def lammps_to_molecule(directory, bondingAtoms, fileName, saveName):
    # Go to file directory
    os.chdir(directory)

    # Load file into python as a list of lists
    with open(fileName, 'r') as f:
        lines = f.readlines()
    
    # Tidy input
    tidiedLines = clean_data(lines)
    
    # Build sectionIndexList
    sectionIndexList = find_sections(tidiedLines)

    # Get original bonds data
    originalBonds = get_data('Bonds', tidiedLines, sectionIndexList)
    
    # Search bond pair
    def pair_search(bond, bondAtom):
        if bond[2] == bondAtom:
            return bond[3]
        elif bond[3] == bondAtom:
            return bond[2]

    # Loop through atomIDs, possible bonds and find valid bonds
    def search_loop(bonds, bondAtom):
        nextBondAtomList = []

        for searchAtom in bondAtom:
            for bond in bonds:
                nextAtomID = pair_search(bond, searchAtom)
                if nextAtomID is not None:
                    nextBondAtomList.append(nextAtomID)
                    # print(nextAtomID)
        
        return nextBondAtomList
            

    # Find bonds involving bonding atoms
    bondDistance = 3

    validAtomSet = set(bondingAtoms)
    edgeAtomSet = set()
    for bondAtom in bondingAtoms:

        # Make bondAtom a list
        newBondAtomList = [bondAtom]
        
        i = 1
        while i <= bondDistance:
            i += 1
            newBondAtomList = search_loop(originalBonds, newBondAtomList)
            if i <= bondDistance:
                # Add list as individual elements
                [validAtomSet.add(val) for val in newBondAtomList]

            else:
                # Determine which of the last obtained atom IDs have more bonds
                # These atoms should be edge atoms
                furthestAtomSet = set(newBondAtomList)
                possibleEdgeAtoms = furthestAtomSet.difference(validAtomSet)
                
                [validAtomSet.add(val) for val in newBondAtomList]

                # Run another loop to determine if possibleEdgeAtoms have other bonds
                for searchAtom in possibleEdgeAtoms:
                    bondCount = 0
                    for bond in originalBonds:
                        nextAtomID = pair_search(bond, searchAtom)
                        if nextAtomID is not None:
                            bondCount += 1
                    if bondCount > 1: # All atoms will have at least one bond
                        edgeAtomSet.add(searchAtom)

    
    # Add refine_data to each stage
    # Test in LAMMPS - this might fail because of energies
    # Check xyz generated by LAMMPS
    
    # Get atoms data
    atoms = get_data('Atoms', tidiedLines, sectionIndexList)
    atoms = refine_data(atoms, 0, validAtomSet)

    # Get new bonds data
    bonds = refine_data(originalBonds, [2, 3], validAtomSet)
    bonds = add_section_keyword('Bonds', bonds)
    
    # Get angles data
    angles = get_data('Angles', tidiedLines, sectionIndexList)
    angles = refine_data(angles, 0, validAtomSet)
    angles = add_section_keyword('Angles', angles)

    # Get dihedrals
    dihedrals = get_data('Dihedrals', tidiedLines, sectionIndexList)
    dihedrals = refine_data(dihedrals, 0, validAtomSet)
    dihedrals = add_section_keyword('Dihedrals', dihedrals)

    # Get impropers
    impropers = get_data('Impropers', tidiedLines, sectionIndexList)
    impropers = refine_data(impropers, 0, validAtomSet)
    impropers = add_section_keyword('Impropers', impropers)

    # Rearrange atom data to get types, charges, coords - assume atom type full very important
    types = [[atom[0], atom[2]] for atom in atoms]
    types = add_section_keyword('Types', types)

    charges = [[atom[0], atom[3]] for atom in atoms]
    charges = add_section_keyword('Charges', charges)

    coords = [[atom[0], atom[4], atom[5], atom[6]] for atom in atoms]
    coords = add_section_keyword('Coords', coords)

    # Get and change header values
    header = tidiedLines[1:6]
    header = [val.split() for val in header]
    # Update numbers with new lengths of data
    for index, data in enumerate([atoms, bonds, angles, dihedrals, impropers]):
        header[index][0] = str(len(data))
    header.insert(0, ['\n'])
    
    # Combine to one long output list
    outputList = []
    totalList = [header, types, charges, coords, bonds, angles, dihedrals, impropers]
    
    for keyword in totalList:
        outputList.extend(keyword)
        
    # Output as text file
    save_text_file(saveName + 'molecule.data', outputList)

lammps_to_molecule('/home/matt/Documents/Oct20-Dec20/Bonding_Test/DGEBA_DETDA/Pre_Reaction', ['32'], 'system.data', 'changed') # '33', '62'